name: redux_thunk
author: Brian Egan <brian@brianegan.com>
description: A Redux.dart Middleware that allows you to dispatch functions that perform async work as actions.
homepage: https://github.com/brianegan/redux_thunk
version: 0.2.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  redux: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.3.0
